import java.util.Arrays;
import java.util.Scanner;

public class Java2025 {
    public static void main(String[] args) {
//First Code
        // System.out.println("Welcome to Takeover");

//Single Line Comment
        //System.out.println("Welcome to Takeover");

//Multiline Comment
        //System.out.println("This is python");
        //To use this, ctrl + shift + /

//Data Types
        /*
        a. Primitive Data Types
        b. Reference Data Types

        PRIMITIVE DATA TYPES
        1. byte(1 byte-> 8bits)
        2. short  (2 bytes-> 16bits)
        3. int  (4 bytes-> 32bits)
        4. long  (8 bytes-> 64bits)
        5. float   (4 bytes-> 32bits)
        6. double  (8 bytes-> 64bits)
        7. boolean  (1 bit)
        8. char    (2 bytes-> 16bits)
        */

//Primitive Data Types Examples
        /*
        byte y = 34; //2^8 to 2^7 // -128 to 127
        byte num1 = 5;
        byte m1 = (byte)(num1+12);

        short m = 3; // -32,768 to 32,767
        short num3 = 10;
        short res3 = (short)(num1 + num3);

        int x = 1565656565; // -2,147,483,648 to 2,147,483,647
        int num4 = 15;

        long num = 483935359; // -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807.

        float p = 23.47f; // 6-7 decimal digits

        double q = 3.14159; // 15 decimal digits
        double res = num1 + 10.5;

        boolean b = true; // Stores true or false values - Used for conditional logic

        char c = 'A'; // Stores a single character/letter or ASCII values
        char c1 = 88;

        System.out.println(c1);
        System.out.println();
        System.out.println(res3);
        */


//REFERENCE DATA TYPES
        /*
        // String: A sequence of characters enclosed in double quotes. It's an object of the String class.
        String str = "Hello";

        // Array: A collection of elements of the same type stored in contiguous memory locations.
        int[] arr = {1, 2, 3};

        // Class: A blueprint for creating objects. Classes define properties and behaviors of objects.
        class Person { };

        // Interface: A reference type that defines a set of methods a class must implement.
        interface Runnable { };

        //Enum: A special data type to define a fixed set of constants.
        enum Colors { RED, BLUE };

        System.out.println(str);
        */

//Naming Convention
        /*
        String name = "ridwan";
        String name1 = "hikmah";
        String myName = "john";  // CAMEL case
        String MyName = "peter";  // PASCAL case
        String MyFirstName = "paul"; // pascal case
        String My_First_Name = "patrick";
        String my_name = "beardy boo";
        String myName1 = "jack";  // note, here myName is an instance or an object of the class String.
        String name12 = new String("alex");
        String phone = new String("Samsung");
        String myName2 = new String("Victor");

        System.out.println(phone);
        System.out.println(my_name);
        */

//User Defined and Inbuilt Class
        /*
        java.lang(all the classes here can be generated by default without importing them) ->Math class and String class.
        java.util(all the classes here must be imported before we can implement them) ->Scanner class.
        note:two types of classes are user defined and inbuilt class.
        */

//Concatenation
        /*
        //Concatenation is the joining of two or more strings
        String my_name = "beardy boo";
        String location = "Lagos";
        int age = 34;
        System.out.println("My name is " + my_name + " and I am in " + location);
        */

//Writing the concatenation example in one print
        /*
        String my_name = "beardy boo";
        int age = 32;

        System.out.println("my name is " + my_name + " and I am " + age + " years old");
        System.out.println();
        //System.out.println("my name is "+ my_new_name+ " and I am learning java");
        System.out.println("my name is Alex and I am learning java");
        System.out.println("my name is Alex" + " and I am learning java");
        */

//Declaration and Definition
        /*
        int x;
        x = 43;
        int y = 5;
        */

//Multivariable Declaration
        /*
        //method 1
        int x6;
        int x7;
        int x8;

        //method 2
        int x1, x2, x3, x4, x5;

        x1 = 4;
        x2 = 7;
        x3 = 9;
        x4 = 2;
        x5 = 1;
        x6 = 17;
        x7 = 90;
        x8 = 785;
        //delimiter = ;
        */

//Multivariable Assignment
        // double y1 = 12.4, y2 = 34.5, y3 = 32;

//Casting
        /*
        Casting is the conversion of one data type to another.
        1. Implicit casting // Automatic type conversion.
        2. Explicit casting // Manual type conversion.

        Implicit casting: Also known as widening. It occurs automatically when you convert a smaller data type to a larger data type.
        byte → short → int → long → float → double
        char → int
        */

        //Implicit Casting Examples
        /*
        byte num1 = 3; //3
        //(-32,034,...-129(-128,...,127)128,...,32,034)
        byte num2 = 5; //5
        short num3 = 10;
        int num4 = 15;
        double b1 = 10.7;
        double res = num3 + 10.5;

        //Implicit + Explicit
        short res3 = (short) (num1 + num2);
         */

        /*
        Explicit casting: Also known as narrowing. It occurs when you convert larger data type to smaller date type.
        double → float → long → int → short → byte
        int → char
        */

        //Examples of Explicit/Manual Casting
        /*
        double price = 99.99;
        byte m1 = (byte) (num2 + 12);
        int discountedPrice = (int) price;  // double → int (manual)

        System.out.println(num1);
        System.out.println(num2);
        System.out.println(num3);
        System.out.println(num4);
        System.out.println(b1);
        System.out.println(res);
        System.out.println(m1);
        System.out.println(res3);
        System.out.println(discountedPrice);
        */

//Input Types
        /*
        String name = "david";
        String name1 = new String("John");
        String info = "  this is my java class   ";
        String info1 = "this is my java class";  // note, indexing always start from 0

        System.out.println(info);
        System.out.println(info + info1);
        System.out.println(5 + 6);
        System.out.println("5" + "6");
        System.out.println("5" + 7);
        System.out.println('5' + "8");
        System.out.println(name + name1);
        */

//String Methods
        /*
        //Note: Int does not have method
        String info = "  this is my java class   ";
        String info1 = "this is my java class";

        System.out.println(info.length());
        System.out.println(info1.length());
        System.out.println(info.trim().length());
        System.out.println(info.toUpperCase());
        System.out.println(info1.indexOf('m'));
        System.out.println(info1.indexOf("java"));
        System.out.println(info1.contains("java"));
        */

        //Another example //Highlighting method inside String Class
        /*
        String my_name = new String ("Iyanu is lovely");
        System.out.println(my_name.startsWith("I")); //Asking if the String starts with I, it will return boolean response.
        */

//Operators
        /*
        1. Arithmetic operators
        2. Assignment operators
        3. Comparison operators
        4. Logical Operators
        5. Bitwise operators
        */

//Arithmetic Operators
        /*
        System.out.println(3+6);
        System.out.println(3*5);
        System.out.println(1/2);
        System.out.println(1.5/2);
        System.out.println(5/2.0);
        System.out.println(3-6);
        System.out.println(13%6); // modulo gives the remainder
        System.out.println(10%2);
        System.out.println(7%17);
        System.out.println(((double)5/2)); //Explicit Castin ongoing
        System.out.println(15%27);
        */

//Assignment Operators
        /*
        int x = 5;
        int y = 13;
        int m = 3;
        int w = 10;

        x = x + 1;   // x+=1 or x++
        y = y-x;     // y-=x or y--
        m = m*x;     // m*=x ;
        w = w/12;    // w/=12;

        System.out.println(x);
        System.out.println(y);
        System.out.println(m);
        System.out.println(w);
        */

//Comparison Operators
        //Example 1
        /*
        int x = 12;
        int y = 14;

        System.out.println(x==y); //False
        System.out.println(x>y);  //False
        System.out.println(x>=y); //False
        System.out.println(x<y);  //True
        */

        //Example 2
        /*
        int x = 3;
        int y = 12;
        int z = 15;

        System.out.println(x==y && x>6);    //False
        System.out.println(x>y && x<6);     //False
        System.out.println(x>=z || y>10);   //True
        System.out.println(!(x>1));         //False
        System.out.println(!(x>y) && x<6);  //True
        System.out.println(!(x>y && x<6));  //True
        */

//Logical Operators
         /*
         a. && (ampersand command) and
         b. || (pipe symbol) or
         c. !  not

        if one of the values is false when dealing with and operator, then the result will be false
         T and T = T
         T and F = F
         F and T = F
         F and F = F

        if one of the values is true when dealing with or operator, then the result will be true
         T or T = T
         T or F = T
         F or T = T
         F or F = F

        Example Code for Logical Operators
         int x = 3;
         int y = 12;
         int q = 15;

        System.out.println(x==y && x>6);       //F
        System.out.println(x>y && x<6);        //F
        System.out.println(x>=q || y>10);       //T
        System.out.println(!(x>1));             //F
        System.out.println(!(x>y) && x<6);     //T
        System.out.println( !(x>y && x <6) );   //T
        */

//Bitwise operator
        /*
        1. &  -> bitwise and
        2. |  -> bitwise or
        3. ^  -> bitwise XOR
        4. << -> left shift
        5. >> ->  right shift
        */

        System.out.println(75 & 58);    //10
        System.out.println(15 & 17);    //1
        System.out.println(12 | 135);   //
        //System.out.println(43 ^ 56);
        //System.out.println(29 << 2);
        //System.out.println(37 >> 3);
        //System.out.println((40 << 2) ^ 25);


//COLLECTING INPUT FROM USER
        /*
        String name = "Grace"; //Note, here name is an object or instance of the class String.
        String name1 = new String("My Grace"); //similarly, name1 is an object or instance of a class String.
        String another_name = new String("My Wife");

        System.out.println("Her name was "+name+". Then, she became "+name1+". And now! "+another_name);
        */

//Creating the Object of a scanner class
        /*
        Scanner info = new Scanner(System.in);

        System.out.println("Fine human, wetin be your name:");
        String new_name = info.nextLine();

        System.out.println("please enter your age:");
        int newage = info.nextInt();

        System.out.println("please enter your gender:");
        String gender = info.next();

        System.out.println("My name is " + new_name + ", I am " + newage + " years old.");
        System.out.println("I am a " + gender);
        */

        //Methods in the scanner class are many, lets check some
        /*
        Scanner homeboy = new Scanner(System.in);

        System.out.println("What is the name of your friend?");
                String checker = homeboy.nextLine();

        System.out.println("Where does he live?");
                String bozer = homeboy.findInLine("Abk");

        System.out.println(checker);
        System.out.println(bozer);
        */

//Math Library
        /*
        double number = Math.pow(2, 4);
        double num1 = Math.pow(3,0);
        double num2 = Math.sqrt(64);
        double num2a = Math.tan(Math.toRadians(45));
        double num2b = Math.sin(Math.toRadians(45));
        double num2r = Math.round(num2*10000.0)/10000.0;
        double num3 = Math.hypot(3,4);  // 9 + 16 = 25, Ans=5
        double res = 127.3452;
        double num3a = Math.round(res);

        System.out.println(number);
        System.out.println(num1);
        System.out.println(num2);
        System.out.println(num2a);
        System.out.println(num2b);
        System.out.println(num2r);
        System.out.println(num3);
        System.out.println(res);
        System.out.println(num3a);

        System.out.println(Math.pow(32, 1/5));
        System.out.println(Math.cbrt(27));
        System.out.println(Math.pow(32, 1.0/5));
        System.out.println(Math.sqrt(100));
        System.out.println(Math.pow(27, 1.0/3));
        System.out.println( (Math.random()));
        System.out.println(Math.random()*15));
        System.out.println( (int) (Math.random()*10));
        */

//Another Example - Receiving info from Users
        /*
        Scanner newInfo = new Scanner(System.in);

        System.out.println("Bros, enter how many pi you wan sell:");
        double x1 = newInfo.nextDouble();

        System.out.println("Enter how much you wan sell am88:");
        double y1 = newInfo.nextDouble();
        System.out.println(x1*y1);
        */

//Simple math
        /*
        Scanner thisInfo = new Scanner(System.in);

        System.out.print("enter the value of x:");
        double x = thisInfo.nextDouble();

        System.out.print("enter the value of y:");
        double y = thisInfo.nextDouble();

        double numerator = Math.pow(x,2) + Math.pow(y,3);
        double denum = x + y;

        double r = Math.sqrt(numerator/denum);
        System.out.println("the value of r is "+ r);   // x = 2, y=3
        */

//Conditional statement
        //🔻FIRST CODE

        /*
        int x = 5;
        int y = 5;

        if(x>y){
            System.out.println("x is greater than y");
        }

        else{
            System.out.println("x="+x+ "is not greater than y="+y+". but thanks for checking");
            }
        */

        //🔻SECOND CODE

        /*
        int x = 5;
        int y = 5;

        if (x>y){
            System.out.println("waooo "+ x + " is greater than "+ y);
            }

        else if(x==y){
            System.out.println(" waooo both of them have the same values ");
            }

        else{
            System.out.println("noooo "+ x + " is not greater than "+ y);
            }
        */

        //🔻THIRD CODE - (Seniority Checker) Accept input from user

        /*
        Scanner checkCon = new Scanner(System.in);
        System.out.println("This program checks who is older between two people");

        System.out.println();
        System.out.print("What is the name of the first person?");
        String nameAge = checkCon.next();

        System.out.print("What is their age?");
        int firstValue = checkCon.nextInt();

        System.out.println("What is the name of the second person?");
        String nameAge2 = checkCon.next();

        System.out.println("What is their age?");
        int secondValue = checkCon.nextInt();

        if (firstValue < secondValue) {
            System.out.println("Hey, " + nameAge + ". You should show some respect to " + nameAge2 + ". They are not your mate");
            }
        else if (firstValue > secondValue) {
            System.out.println("Hi,"+nameAge+". You are the Boss and you are older than "+nameAge2);
            }
        else {
            System.out.println("Lol, you are both the same age. Just shake hands and be friends");
            }
        */

        //🔻FOURTH CODE (A program to Check Age)

        /*
        Scanner sc = new Scanner(System.in);
        System.out.println("This program checks how old you are and then give an appropriate remark.");
        System.out.println();

        System.out.print("enter your age:");
        int age = sc.nextInt();

        if(age<10){
            System.out.println("you are a kid ");
            }

        else if(age>=10 && age <18){
            System.out.println(" you are still a Baby!");
            }

        else if(age>=18 && age <30){
            System.out.println(" you are an adult but still young!");
            }

        else if(age>=30 && age <45){
            System.out.println(" you are an adult but somehow old!");
            }

        else{
            System.out.println("you are very old");
            }
         */

//Sunday 19th, 2025
//🔻How to check the class of an object

        /*
        String aname = "Iyanu";
        System.out.println(aname.getClass().getSimpleName());
        System.out.println(aname.getClass().getName());
        System.out.println(aname.getClass().getName());
        */

//🔻BMI Calc

        /*
        Scanner sc = new Scanner(System.in);

        System.out.println("Enter your weight in kg:");
        double w = sc.nextDouble();

        System.out.println("Enter your height in m:");
        double h = sc.nextDouble();

        double bmi = w/Math.pow(h,2);
        double bmi2 = w/(h * h);
        System.out.println("Your "+bmi+ ". Emphasis: "+bmi2);
        //Testing Conditional Statement

        if (bmi < 18) {
            System.out.println("Your bmi is " + bmi + ". You are underweight, try find something chop, shey you self like am as you lean like cane?");
            }
        else if (bmi >= 18 && bmi < 25) {
            System.out.println("Your bmi is " + bmi + ". Your health dey alright, you can slap police, you get the strength!");
            }
        else if (bmi >= 25 && bmi < 30) {
            System.out.println("Your bmi is" + bmi + ". You are a fat ass pig, you possibly can't run to save your own life.Aaaargh");
            }
        else {
            System.out.println("Your bmi is " + bmi + ". Chai! Your health is in critical hospital emergency ward level condition.");
            }
        */

//NESTED CONDITIONAL STATEMENT - PRINT EVEN NUMBERS
        //🔻FIRST CODE

        /*
        Scanner scan = new Scanner(System.in);

        System.out.println("Enter a value:");
        int num = scan.nextInt();

        if (num > 20) {
            if (num % 2 == 0){
                System.out.println(num + " is an even number and, it is more than 20");
            }
            else {
                System.out.println(num+ " is not an even number, it is odd");

            }
        }
        */

        //🔻SECOND CODE
        /*
        Scanner sc = new Scanner(System.in);

        System.out.print("enter any value:");
        int num = sc.nextInt();

        if(num>20) {
            if (num % 2 == 0) {
                System.out.println(num + " is an even number and more than 20");
            }

            else if (num % 3 == 0) {
                System.out.print(num + " is divisible by 3 and more than 20");
            }

            else {
                System.out.println(num + " is not an even number and not divisible by 2 and 3 but it is more than 20");
            }
            }
        */

        //🔻THIRD CODE - A code for username & password

        /*
        Scanner sc = new Scanner(System.in);

        System.out.print("enter username: ");
        String userName = sc.nextLine();

        System.out.println("enter password: ");
        String pass = sc.nextLine();

        if(userName.equals("admin")) {
            if (pass.equals("ridwan")) {
                System.out.println("Login successful, thank you admin");
            }

            else if (pass.equals("1234")) {
                System.out.println("This password is wrong. Try another one");
            }
               //take note of this block
            else if (pass != "ridwan") {
                System.out.println("This password is incorrect too");
            }
                //block ends here

            else {
                System.out.println("incorrect password!");
            }
        }

        else{
            if(userName.equals("guest")){
                if(pass.equals("guest")){
                    System.out.println("Login successful, thank you Guest");
                }

                    else if(pass.equals("1234")) {
                        System.out.println("This password is not right. Try another one guest");
                    }

                else{
                        System.out.println("incorrect password guest!");
                    }
            }

            else{
                        System.out.println("Unknown user!");
                        }
                        }
            */

        //🔻FOURTH CODE (Program to check username and password using the .startsWith(" ") method

        /*
        Scanner sc = new Scanner(System.in);

        System.out.print("enter username: ");
        String userName = sc.nextLine();

        System.out.println("enter password: ");
        String pass = sc.nextLine();

        if (userName.startsWith("A")) { //this condition checks if the password 'admin' starts with capital A
            //if(userName.startsWith("A")&&(userName.equals("Admin"))) { //this checks if its starts with capital A & if it is 'admin'
            if (pass.equals("ridwan")) {
                System.out.println("Login successful, thank you admin");
            } else if (pass.equals("1234")) {
                System.out.println("This password is wrong. Try another one");
            }

            //take note of this block
            else if (pass != "ridwan") {
                System.out.println("This password is incorrect");
            }
            //block ends here

        } else {
            if (userName.equals("guest")) {
                if (pass.equals("guest")) {
                    System.out.println("Login successful, thank you Guest");
                } else if (pass.equals("1234")) {
                    System.out.println("This password is not right. Try another one guest");
                } else {
                    System.out.println("incorrect password guest!");
                }
            } else {
                System.out.println("Unknown user!");
            }
        }
        */

//🔻Assignment (My Own)

        /*
        Scanner calc = new Scanner(System.in);

        System.out.println("What is the value of x");
        int x = calc.nextInt();

        System.out.println("What is the value of y");
        int y = calc.nextInt();

        System.out.println("What is the value of z");
        int z = calc.nextInt();

        double up = Math.sqrt (x + Math.pow(y,2) + Math.pow(z,3));
        double win = Math.pow(2,y); //2 raise to power of y
        double kin = Math.pow(y,2); //y raise to the power of

        double down = (2 * Math.pow(x,3)) + Math.cbrt(y) + z;
        double inner = up/down;
        double all = Math.pow(inner,0.25);

        System.out.println(all);
        System.out.println();
        System.out.println(win);
        System.out.println(kin);
        */

//🔻Assignment (Teacher solution)
          /*
          Scanner sc = new Scanner(System.in);

          System.out.print("enter value of x:");
          double x = sc.nextDouble();

          System.out.print("enter value of y:");
          double y = sc.nextDouble();

          System.out.print("enter value of z:");
          double z = sc.nextDouble();

          double num1 = x + Math.pow(y,2) + Math.pow(z,3);
          double numerator = Math.sqrt(num1);
          double denum = 2*Math.pow(x,3) + Math.pow(y,1.0/3) + z;
          double val =  numerator/denum ;
          double result = Math.pow(val, 1.0/4);
          //double result = Math.pow( (Math.sqrt(x + Math.pow(y,2) + Math.pow(z,3)))/(2*Math.pow(x,3) + Math.pow(y,1.0/3) + z), 1.0/4);

          System.out.println("the final result is "+result);
          */

//Sunday, January 26
//Switch Case and Ternary Operator

//SWITCH CASE
        //🔻EXAMPLE 1
        //This code prints the no. of which day of the week you type. It is case sensitive

        /*
        Scanner sc = new Scanner(System.in);

        System.out.println("enter the day of the week:");
        String day_of_the_week = sc.nextLine();

        switch (day_of_the_week) {

            case "sunday":
                System.out.println("this is the first day of the week");
            break;

            case "monday":
                System.out.println("this is the second day of the week");

            case "tuesday":
                System.out.println("this is the third day of the week");
                break;

            case "wednesday":
                System.out.println("this is the fourth day of the week");
                break;

            case "thursday":
                System.out.println("this is the fifth day of the week");
                break;

            case "friday":
                System.out.println("this is the sixth day of the week");
                break;

            case "saturday":
                System.out.println("this is the seventh day of the week");
                break;

            default:
                System.out.println("this is not a valid day of the week");
        }
        */

        //🔻EXAMPLE 2

        /*
        Scanner sc = new Scanner(System.in);

        System.out.print("enter the day of the week :");
        int day = sc.nextInt();

        switch(day){
            case 1:
                System.out.println("today is sunday");
                break;

            case 2:
                System.out.println("today is monday");
                break;

            case 3:
                System.out.println("today is tuesday");
                break;

            case 4:
                System.out.println("today is wednesday");
                break;

            case 5:
                System.out.println("today is thursday");
                break;

            case 6:
                System.out.println("today is friday");
                break;

            case 7:
                System.out.println("today is saturday");
                break;

            default:
                System.out.println("this is invalid!");
        }
        */

//TERNARY OPERATOR
        // condition ? true : false

        //🔻EXAMPLE ONE
        /*
        int x = 2;
        int y = 4;

        String info = (x>y) ? "waoh, it is!" : "noooo, it isn't";
        System.out.println(info);
        */

        //🔻EXAMPLE TWO (Accept Input from User)
        /*
        Scanner win = new Scanner(System.in);

        System.out.println("what is the value of your x?");
        int x = win.nextInt();

        System.out.println("What is the value of your y?");
        int y = win.nextInt();

        String info = (x>y) ? "waoh, x is greater than y!" : "noooo, x is not greater than y";
        System.out.println(info);
        */

        //🔻EXAMPLE THREE (Accept Input from User2)
        /*
        Scanner win = new Scanner(System.in);

        System.out.println("what is the value of your x?");
        int x = win.nextInt();

        System.out.println("What is the value of your y?");
        int y = win.nextInt();

         if(x>y){
               System.out.println("waooooooo");
                }
                else{
               System.out.println("yeahhhhhhhhh");
                }
        */

//FOR LOOP; WHILE LOOP; DO WHILE; ENHANCED FOR LOOP
        //TYPES OF LOOPS
        /*
        1. For loop //we use for loop when we know the exact number of sequence
        2. While loop //we use while loop when the number of sequence is unknown
        3. Do While loop
        4. Enhanced For Loop
         */

//FOR LOOP -> Initialization, Condition and Update(Increment or Decrement)

        //🔻EXAMPLE ONE (Print "I like Java" 5 times)
        /*
        for(int i=1;i<6;i++){
        System.out.println("I like java");
        }
        System.out.println();
        System.out.println("bye for now");
        */

        //🔻EXAMPLE ONE B (Program to print Java Sweet o, 3 times on interval
        /*
        for(int i=0;i<3;i++) {
            for (int j = 0; j < 3; j++) {
                System.out.println("Java sweet o");
            }

            System.out.println();
            System.out.println("bye for now");

        }
        System.out.println("no more iteration");
        */

        //🔻EXAMPLE TWO (Print "I love Java" and number it accordingly)
        /*
        for(int i=1;i<6;i++){
             System.out.println(i+": I like java");
         }
        */

        //🔻EXAMPLE THREE (Print Even numbers between 1 and 11)
        /*
        for(int j=1;j<11;j++){

             if(j%2==0){
                 System.out.print(j+" ");
             }
        }
        */

        //🔻EXAMPLE FOUR (Print all Even&Odd numbers between 1 and 11 & label it with "is an even number")
        /*
        for(int j=1;j<11;j++){

             if(j%2==0){
                 System.out.println(j+" is an even number");
             }

             else{
                 System.out.println();
                 System.out.println(j+" is an odd number");
             }
        }
        */

        //🔻EXAMPLE FIVE (Print "I like Java" five times, while labelling from 5 to 1)
        /*
        for(int i=5;i>0;i--){
             System.out.println(i+": I like java");
        }
        */

        //🔻EXAMPLE SIX (Program to check if a number is divisible by 3,5 or 3only or 5only
        /*
        Scanner num = new Scanner(System.in);

        System.out.print("enter any value:");
        int val1 = num.nextInt();

        if(val1%3==0){
               System.out.print("this is divisible by 3");
                if(val1%5==0){
                    System.out.print(" and divisible by 5");
                }
        }

        else if(val1%5==0){
               System.out.println("this is divisible by 5 only");
        }
        */

        //🔻EXAMPLE SEVEN (Program to check if a number is divisible by 3,5 or 3only or 5only)
        /*
        Scanner num = new Scanner(System.in);

        System.out.print("enter any value:");
        int val1 = num.nextInt();

        if(val1%3==0 && val1%5==0){
               System.out.println("this is divisible by 3 and 5");
        }

        else if(val1%5==0){
               System.out.println("this is divisible by 5 only");
        }

        else if(val1%3==0){
               System.out.println("this is divisible by both 3 only");
        }
        */

        //🔻EXAMPLE EIGHT (Program to print 1 to 10)
        /*
        for(int i=1; i<11; i++){
            //System.out.println(i); //On different line
            System.out.print(i+" "); //Same line with space
        }
        */

        //🔻EXAMPLE NINE (Program to print sum of all values from 1 to 5 - Print result only)
        // We printed result only by putting the sout out of the loop
        /*
        int sum = 0;
        for (int i=1;i<=5;i++){
               sum+=i;  // sum=sum+1=15
            //sum0i1=1 start
            //sum1i2=3
            //sum3i3=6
            //sum6i4=10
            //sum10i5=15 stop
        }
        System.out.println(sum);
        */

        //🔻EXAMPLE TEN (Product of all  the values from 1 to 5)
        /*
        int product = 1;
        for(int j=1; j<5;j++){
            product*=j; // product = product*j : product = 24
            //prod1j1 start
            //prod1j2
            //prod2j3
            //prod6j4
            //prod24j5 stop
            System.out.println(product);
        }
        */

        //🔻EXAMPLE ELEVEN (Product of all  the values from 5 to 8)
        /*
         int product = 1;

          for(int j=5; j<9;j++){
              product*=j; // product = product*j
              //prod1j5 Initials
              //prod5j6 = 30
              //prod30j7 = 210
              //prod210j8 = 1680
              // product = 1680
          }
          System.out.println(product);
        */

        //🔻EXAMPLE TWELVE (Let us print even numbers from 1 to 10)
        /*
        for(int j=1; j<11; j++){
            if (j % 2 == 0) {
                //System.out.println(j); //On different line
                System.out.print(j + " "); //Same line with space
            }
        }
        System.out.println("QED");
        */

        //🔻EXAMPLE THIRTEEN (Program to check if a user given number is divisible by 3,5 or both)
        /*
        Scanner tester = new Scanner(System.in);

        System.out.println("enter the number");
        int num = tester.nextInt();

            if (num % 3 == 0) {
                System.out.println("This number is a multiple of 3");
            }//On different line

            if (num % 5 == 0) {
                System.out.println("This number is a multiple of 5");
            }

            if ((num % 3 == 0) && (num % 5 == 0)) {
                System.out.println("This number is a multiple of 3 and 5");
            }

            else if ((num % 3 != 0) && (num % 5 != 0)) {
                System.out.println("This number is jaga jaga, ko wulo inside this code");
             }
        */

        //🔻EXAMPLE FOURTEEN (Print the sum of all even and the product aod all odd between one and any given number)
        /*
        Scanner input = new Scanner(System.in);

        System.out.print("enter any value:");
        int num = input.nextInt();   // 5

        int sumOfEven = 0;
        int productOfOdd = 1;

        for(int j=1; j<=num; j++){

            if(j%2==0){
                sumOfEven+=j;  // sumOfEven = sumOfEven + j
                //0+2 = 2
                //2+4 = 6
            }

            else{
                productOfOdd*=j; // productOfOdd= productOfOdd * j //15
                //1*1=1
                //1*3=3
                //3*5=15
            }

        }

        System.out.println ("sum of all the even numbers from 1 to "+ num +" is:"+sumOfEven);
        System.out.println ("product of all the odd numbers from 1 to "+ num +" is:"+productOfOdd);
         */

//2 Feb, 2025
        //🔻EXAMPLE 15 (Program to prints all numbers divisible by 3, then by 5 for any given number)

        /*
        Scanner input = new Scanner(System.in);

        System.out.println("Enter number");
        int dnum = input.nextInt();

        for (int j=1; j<=dnum;j++){
        if (j % 3 == 0){
            System.out.print(j+ " ");
        }
        }
        System.out.println();

        for (int i=1; i<=dnum; i++){
        if (i%5==0){
            System.out.print(i+" ");
            }
        }
        System.out.println();
        System.out.println("Those are the numbers divisible by 3 & 5 in " + dnum);
        */

        //🔻EXAMPLE 16 (A code to give the sum of all the numbers divisible by 3 and 5 from 1 to the number collected from the user)
        /*
        Scanner input = new Scanner(System.in);

        System.out.println("Enter a value:");
        int num = input.nextInt(); //15

        int sumOfNum = 0;
        for(int m=1; m<=num; m++){

            if(m%3==0 && m%5==0){
                sumOfNum+=m;
                //since its 15 thats divisible by 3&5
                //0+15=15
            }

        }
        System.out.println("sum of all the values that are divisible by 3 and 5 from 1 to "+num+" is "+sumOfNum);
        */

//NESTED FOR LOOP
        //🔻EXAMPLE 17 (This program demonstrate loop in loop)
        /*
        for(int i =0; i<3;i++){
            for(int j=0;j<3;j++){
                System.out.println("We dey inside count 0");
            }
            System.out.println();
            System.out.println("On - to the next one");
            System.out.println();
        }
        System.out.println("Iteration is done");
        */

        //🔻EXAMPLE 18 (A program that allows gives you 4 chances to input the correct name required by the program)
        /*
        Scanner myscanner1 = new Scanner(System.in);
        System.out.println("your name: ");
        String name1 = myscanner1.nextLine();

        int c=0;

        while(!(name1.equals("david"))) {
            System.out.println("enter correct name please: ");
            name1 = myscanner1.nextLine();
            c += 1;

            if (c > 2 && !(name1.equals("david"))) {
                System.out.println("you have exhausted your trials, try in the next 15 minutes");
                break;
            }

            else if (c>2 && (name1.equals("david"))){
                System.out.println(name1+" now you are talking!");
                break;
            }
        }
        */

        //🔻EXAMPLE 19 (A program to print a countdown, like 4$, 3$, 2$, $
        /*
        for (int i = 4; i > 0; i--) {
            for (int j = 0; j < i; j++) {
                System.out.print("$" + " ");
                System.out.println();
            }
            System.out.println();
        }
        */

        //🔻EXAMPLE 20 (This program uses loop in loop)
        //This program uses loop to do a form of drawing
        // # # # #
        // # # # #
        // # # # #
        // # # # #
        //note: println and print will give totally different results (print alone works for this purpose)
        /*
        for(int k=0;k<4;k++){
            for(int m=0;m<4;m++){
                System.out.print("# "); //This prints horizontally
            }
            System.out.println();
        }
        */

        //🔻Method2
        /*
        for (int i=0;i<4;i++) {
            System.out.println("# # # #");
        }
        */

        //🔻EXAMPLE 21 (This program uses loop in loop)
        //This program prints Pattern like this:
        // #
        // # #
        // # # #
        // # # # #
        /*
        for(int k=1;k<5;k++){
            for(int m=0;m<k;m++){
                System.out.print("# ");
            }
            System.out.println();
        }
        */

        //🔻EXAMPLE 22 (This program uses loop in loop)
        /*
        int num =15;
        for (int m=2; m<num; m++){
            if (m % 2 == 0) {
                System.out.println(m);
            }
            else {
            System.out.println("next");
            }
        }
        System.out.println();
        System.out.println("Thats all!");
        */

        //🔻EXAMPLE 23 (My attempt of a program to print all prime numbers between 1 and 20
        /*
        for (int i=2; i<20; i++){
            if (i/1==i && i%i==0 && i%2!=0 && i%3!=0){
                System.out.print(i + ", ");
            }
        }
        */

        //🔻EXAMPLE 24 (Solution: A Program to print all prime numbers between 1 and 20)
        /*
        int val = 20;
        for(int i=2; i<val; i++){
            int c = 0;
            for(int j=1; j<i+1; j++){
                        if (i%j==0){
                            c += 1;
                        }
            }

            if (c==2){
                        System.out.println(i);
        //The logic of this code is to check if i(an integer) is less than the value given (20 in this case) and then process all the prime numbers
        //between 1 and that value, then, for(int j=1;j<i+1;j++) is the counter for the number we want to check. We want to check if the number is
        //divisible by 1 and only one other number - which is itself.
        //if(c==2) is used to confirm that it is only 2 numbers that can divide the i in check.

                        //(i=2, i<20 - c=0, (j=1,j<2+1=3) - 2/1=2r0, c=0+1=1, j++=2
                        //                  (j=2,j<2+1=3) - 2/2=1r0, c=1+1=2, j++=3
                        //                  (j=3,j!<2+1=3)- out
                        //                  (c==2 - Print i=2), i++=3

                        //(i=3, 3<20 - c=0, (j=1,j<3+1=4) - 3/1=3r0, c=0+1=1, j++=2
                        //                  (j=2,j<3+1=4) - 3/2=1r1, skip, j++=3
                        //                  (j=3,j<3+1=4) - 3/3=1r0, c=1+1=2, j++=4
                        //                  (j=4,j!<3+1=4)- out
                        //                  (c==2 - Print 1=3), i++=4

                        //(i=4, 3<20 - c=0, (j=1,j<3+1=4) - 3/1=3r0, c=0+1=1, j++=2
                //                  (j=2,j<3+1=4) - 3/2=1r1, skip, j++=3
                //                  (j=3,j<3+1=4) - 3/3=1r0, c=1+1=2, j++=4
                //                  (j=4,j!<3+1=4)- out
            }
        }
        */

//🔻ASSIGNMENT: Collect an integer from the user, then give the sum of all prime numbers from 1 to that number
//🔻My Attempt - Correct!😍💪

        Scanner prime = new Scanner(System.in);

        System.out.println("Provide any Integer:");
        int num = prime.nextInt();

        int sumOfNum = 0;
        for (int i=2; i<num; i++){
            int c = 0;
            for (int j=1; j<i+1; j++){
                if (i%j==0){
                    c += 1;
                }
            }

            if (c == 2) {
                sumOfNum+=i;
            }
        }
        System.out.println("the sum of all is " + sumOfNum+ " ");


//🔻Teachers Solution
        /*
        Scanner input = new Scanner(System.in);
        System.out.println("enter any value: ");

        int num = input.nextInt();
        int sum_of_prime =0;
                for (int i=2; i<num; i++){
                    int c=0;
                            for (int j=1; j<i+1; j++){
                                if(i%j==0){
                                    c+=1;
                                }
                            }
                   if (c==2){
                       sum_of_prime+=i;
                   }
                }
        System.out.println(sum_of_prime);
        */

//WHILE LOOP
        //We follow the usual way for For loop - initialization;condition;update
        //🔻Example 1
        /*
        int i=1;
        while (i<5){
            System.out.println("I love coding baje");
            i++; //i=i+1
        }
        System.out.println("Bye");
        */

        //🔻Example 2 (A program to ask for a certain name, using assignment operator == to check/no limit to trial times)
        /*
        Scanner prawn = new Scanner(System.in);

        System.out.println("Jo, kiloruko re: ");
        String name = prawn.nextLine();

        while ((name.toLowerCase().equals("david"))==false) {
            System.out.println("enter correct name ejo: ");
            name = prawn.nextLine();
        }
        System.out.println("heloo " + name);
        */

        //🔻Example 3 (A program to ask for a certain name, using assignment operator not(!) to check/no limit to trial times)
        /*
        Scanner prawn = new Scanner(System.in);

        System.out.println("Jo, kiloruko re: ");
        String name = prawn.nextLine();

        while(!(name.toLowerCase().equals("david"))){
            System.out.println("enter correct name please: ");
            name = prawn.nextLine();
        }
        System.out.println(name.toLowerCase()+" you are correct!");
        */

        //🔻Example 4
        /*
        Scanner prawn = new Scanner(System.in);

        System.out.println("Jo, kiloruko re: ");
        String name = prawn.nextLine();

        int c=0;
        while(!(name.equals("david"))){
            System.out.println("enter correct name please: ");
            name = prawn.nextLine();
            c+=1;

            if (c>2 && !(name.equals("david"))){
                System.out.println("you have exhausted your trials");
                break;
            }
            else if (c>2 && (name.equals("david"))){
                System.out.println(name+" now you are talking, try in the next 15mins.");
                break;
            }
        }
        //System.out.println(name+" you are correct!");
        if (c>2){
            System.out.println(" ");
        }

        else {
            System.out.println(name.toLowerCase() + " you are correct!");
        }
        */

//Assignment: Write a Java program that calculate the Average Grace Point (AGP) of a student based on the scores entered by the user
//🔻My Attempt
        /*
        Scanner okay = new Scanner(System.in);

        System.out.println("We want to calculate your average GP. Okay? No panic.");
        System.out.println();

        System.out.println("Kilogba ninu math over 100:");
        int num = okay.nextInt();

        System.out.println("English nko? over 100:");
        int num0 = okay.nextInt();

        System.out.println("What about physics? over 100");
        int num1 = okay.nextInt();

        System.out.println("Now Chemistry? over 100");
        int num2 = okay.nextInt();

        System.out.println("lastly, Biology, over 100");
        int num3 = okay.nextInt();

        int total = num+num0+num1+num2+num3;
        double agp = total/5;

        if (agp>1 && agp<20) {
            System.out.println("Who is paying your school fees self?");
            System.out.println("This your average is okay for you to drop out now o");
            System.out.println("anyways, your AGP is: " + agp);
        }
        if (agp>=20 && agp<=40){
            System.out.println("Your AGP is: "+ agp +"(F)");
            System.out.println("You need to put in serious effort if you don't want to drop out.");
            System.out.println("Your are carrying this course");
        }
        if (agp>=40 && agp<=45){
            System.out.println("Your AGP is: "+agp +"(E)");
        }
        if (agp>=46 && agp<50){
            System.out.println("Your AGP is: "+agp +"(D)");
        }
        if (agp>=50 && agp<60){
            System.out.println("Your AGP is: "+agp +"(C)");
        }
        if (agp>=60 && agp<70){
            System.out.println("Your AGP is: "+agp +"(B)");
        }
        if (agp>=70 && agp<=80){
            System.out.println("Wow! Your AGP is: "+agp +"(A)");
        }
        if (agp>=80){
            System.out.println("Absolutely mindblowing😍!!!. Your AGP is: "+agp +"(On Steroid)");
        }
        */

        //🔻Assignment: Write a Java program that asks how many course a user is offering, ask the individual scores they got in each course.
        //Calculate the Average Grace Point (AGP) the student based on the scores entered by the user
        //🔻My Attempt
        /*
        Scanner okay = new Scanner(System.in);

        System.out.println("We want to calculate your average GP. Okay? No panic.");
        System.out.println();

        System.out.println("How many subject are you offering?");
        int j = okay.nextInt();

        int sumofj=0;
        for (int i=0;i<j;i++){
            System.out.println("What is the subject:");
            String sub1 = okay.next();
            System.out.println("What did you score over 100:");
            int j1= okay.nextInt();

            sumofj+=j1;

        }
        double agp = sumofj/j;

        if (agp<20) {
            System.out.println("Who is paying your school fees self?");
            System.out.println("This your average is okay for you to drop out now o");
            System.out.println("anyways, your AGP is: " + agp);
        }
        if (agp>=20 && agp<=40){
            System.out.println("Your AGP is: "+ agp +"(F)");
            System.out.println("You need to put in serious effort if you don't want to drop out.");
            System.out.println("Your are carrying this course");
        }
        if (agp>=40 && agp<=45){
            System.out.println("Your AGP is: "+agp +"(E)");
        }
        if (agp>=46 && agp<50){
            System.out.println("Your AGP is: "+agp +"(D)");
        }
        if (agp>=50 && agp<60){
            System.out.println("Your AGP is: "+agp +"(C)");
        }
        if (agp>=60 && agp<70){
            System.out.println("Your AGP is: "+agp +"(B)");
        }
        if (agp>=70 && agp<=80){
            System.out.println("Wow! Your AGP is: "+agp +"(A)");
        }
        if (agp>=80){
            System.out.println("Absolutely mindblowing😍!!!. Your AGP is: "+agp +"(On Steroid)");
        }
        */

//🔻Teacher Solution
        /*
        Scanner tbd = new Scanner(System.in);

        System.out.println("enter the number of subjects:");
        int num_of_subject = tbd.nextInt();

        double total_scores = 0;
        for (int i=1;i<=num_of_subject;i++) {
            System.out.println("enter the score for the subjects:");
            double subject_score = tbd.nextDouble();
            total_scores += subject_score;

        }
        double avg=total_scores/num_of_subject;
        System.out.println("The average grade for "+num_of_subject+" subjects is given as "+avg);
        */

//Assignment 2: Use while loop for the AGP problem - not done

//🔻NESTED WHILE LOOP
        //🔻CODE1
        /*
        int i=1;
        while (i<4){
            int j=0;
            while (j<2){
                System.out.println("Helooo Java");
                j++;
            }
            System.out.println("Bus Stop!");
            i++;
        }
        System.out.println(" final bus stop!!!");
        */

//🔻BREAK & CONTINUE
//🔻USING BREAK: The break function will terminate the loop if the condition set for the break function is met.
        //🔻CODE2: a program to print 1 to 4 using "break"
        /*
        for (int i=1; i<10; i++){
            if (i==5){
                System.out.println("end of iteration");
                break;
            }
            System.out.println(i);
        }

//🔻USING CONTINUE: Continue will skip the process if the condition set for it is met. This program for example will print 1,2,3,4 (skip 5) 6,7,8,9
        //🔻CODE3: A program to print 1 to 4 & 6 to 9, skipping 5 using "continue"
        /*
        for (int i=1; i<10; i++){
            if (i==5){
                continue;
            }
            System.out.println(i);
        }
        */

//🔻Class work
        //🔻CODE 4: A program to print all even numbers from 1 to 15
        /*
        int num=15;
        for (int m=1; m<num; m++){
            if (m%2==0){
                System.out.println(m);
            }
        }
        */

        //🔻CODE 5:A program to print even numbers between 1 and 15 using "continue"
        /*
        for(int i=1; i<15;i++){

            if(i%2!=0) {
                continue;
            }

            System.out.println(i);
        }
        */

//🔻D0...WHILE LOOP
        //When we are using do,while loop, the code will be executed at least once because the code comes before the condition
        //This particular code will run twice, but if the int 1=12, it will run one time before it stops cos the i!<3

        //do while 1
        /*
        int i=1;

        do{
            System.out.println("Welcome to Java class");
            i++; //i=i+1
        }
        while(i<3);
        */

        //do while 2
        /*
        int i=12;

        do{
            System.out.println("Welcome to Java class");
            i++; //i=i+1
        }
        while(i<3);
        */

        //🔻REMINDER on while loop
        /*
        int j=1;
        while (j<5){
            System.out.println(j);
            j++;
        }
        */

//🔻ARRAYS
        /*
        int x=5;
        int y=6;
        int a=7;
         */

        //🔻ONE DIMENSIONAL ARRAY
        //Array is a collection of many element together and the syntax is written as below:
        /*
        int [] array1 = new int[4];
        // datatype [] arrayname = new datatype[]
        array1[0]=34;
        array1[1]=44;
        array1[2]=23;
        array1[3]=56;

        //another way to write an array is
        int[] my_array = {90,79,89,800};

        //When you define a variable in a program, it will allocate a space for the variable on the system: Memory Address
        //these variable are store in the heap memory of the jvm (java virtual machine)
        //java is split into java development kit (jdk), java runtime environment(jre), & jvm
        //jvm is divided into stack memory and heap memory

        //

        //System.out.println(array1);
        System.out.println(Arrays.toString(array1));

        String [] array3 = {"apple", "banana", "orange"};
        System.out.println(Arrays.toString(array3));
         */
//MULTI-DIMENSIONAL ARRAY
        /*


        Indexing
                            column c0   column c1
                    row r0  rc[0][0]    rc[0][1]
                    row r1  rc[1][0]    rc[1][1]

           We will print the below in the next code
            2   10  24
            12  20  28 this is a 2 by 3
        */

        //🔻TWO DIMENSIONAL ARRAY
        /*
        int [][] myarray7 = new int[2][3];

        myarray7[0][0]=2;
        myarray7[0][1]=10;
        myarray7[0][2]=24;
        myarray7[1][0]=12;
        myarray7[1][1]=20;
        myarray7[1][2]=28;

        int [][] myarray8 = {{3,4,5,10},{2,14,8}};
        String name = "Mama";
        System.out.println(Arrays.deepToString(myarray7));
        System.out.println(Arrays.deepToString(myarray8));
        System.out.println(Arrays.toString(myarray8[0]));
        System.out.println(Arrays.toString(myarray8[1]));
        System.out.println(name+" "+myarray8[1][1]+" "+myarray8[0][2]);
        */

        //🔻LOOPING THROUGH AN ARRAYS
        //Looping through 1-dim Array1
        /*
        String [] myarray1 = {"python", "java", "kotlin", "javascript", "c++", "php"};

        for (int i=0;i<6;i++){
            System.out.println(myarray1[i] + " "+"is a programming language");
        }

        //We will notice that if we add another element to myarray1 which makes it more than the 6 we set, it will ignore it in the output
        //For this, we see that if we add any new element, the program will still work accordingly
        */

        //Looping through 1-dim Array2
        /*
        String [] myarray1 = {"python", "java", "kotlin", "javascript", "c++", "php","swift"};

        for (int i=0;i<myarray1.length;i++){
            System.out.println(myarray1[i] + " "+"is a programming language");
        }
        */

        //Looping through 2-dim Array3
        /*
        String [][] myarray2 = {{"python","java"},{"kotlin","javascript","c#"},{"Go","Ruby","C++"}};
        for (int i=0; i<myarray2[i].length;i++){
            for(int j=0;j<myarray2[i].length;j++){
                System.out.println(myarray2[i][j]);
            }
            System.out.println("bye for now");
        }
        */

        //Assignment 1: Looping through multi-dimensional arrays I
        /*
        String [][][] my_array3 = {{{"python","java"},{"kotlin","javascript"}},{{"C++","C#"},{"Ruby","Dart"}}};
        for (int i=0; i<my_array3[i].length;i++){

            for(int j=0;j<my_array3[i].length;j++){
                System.out.println(Arrays.deepToString (my_array3[i][j]));
            }
            System.out.println("bye for now");
        }
        */

        //Teachers Solution
        /*
        String [][][] my_array3 = { {{"python","java","R","Swift"},{"kotlin","javascript"}}, {{"C++","C#"},{"Ruby","Dart"}} };
        for (int i=0; i<my_array3.length;i++){

            for (int j=0; j<my_array3[i].length; j++){
                for (int k=0; k<my_array3[i][j].length; k++) {
                    System.out.println(my_array3[i][j][k]);
                }
                System.out.println("bye for now");
                System.out.println();
            }
            System.out.println("bye for now, once again");
        }
        System.out.println("bye finally");
         */

        //Assignment 1b: Using enhanced for loop
        /*
        String [][][] my_array3 = {{{"python","java"},{"kotlin","javascript"}},{{"C++","C#"},{"Ruby","Dart"}}};
        for (String[][] ion :my_array3) { //why double array?

            for (String[] koko : ion){

                System.out.println(Arrays.deepToString (koko)+" ");
            }
            System.out.println();
        }
        */

        //Teachers Solution
        /*
        String [][][] my_array3 = {{{"python","java","R","Swift"},{"kotlin","javascript"}},{{"C++","C#"},{"Ruby","Dart"}}};
        for (String ion[][] :my_array3) { //why double array?

            for (String koko[] : ion) {
                for (String kaka : koko) {
                    System.out.println(kaka);
                }
                System.out.println("bye for now");
            }
            System.out.println("Bye, once again");
        }
        System.out.println("Bye, finally");
        */

        //Assignment 2: Looping through multi-dimensional arrays II
        /*
        String [][][][] my_array4 = {{{{"python","java"},{"kotlin","javascript"}},{{"C++","C#"},{"Ruby","Dart"}}},{{{"Python","java"},{"kotlin","javascript"}},{{"C++","C#"},{"Ruby","Dart"}}}};

        for (int i=0; i<my_array4[i].length;i++){

            for (int j = 0; j < my_array4[i].length; j++){
                System.out.println(Arrays.deepToString(my_array4[i][j]));
            }
            System.out.println("bye for now");
        }
        */

        //Teachers Solution:
        /*
        String [][][][] my_array4 = {{{{"python","java"},{"kotlin","javascript"}},{{"C++","C#"},{"Ruby","Dart"}}},{{{"Python","java"},{"kotlin","javascript"}},{{"C++","C#"},{"Ruby","Dart"}}}};
        for (int i=0; i<my_array4.length;i++){

            for (int j=0; j<my_array4[i].length; j++){
                for (int k=0; k<my_array4[i][j].length; k++) {
                        for (int l=0; l<my_array4[i][j][k].length; l++){
                            System.out.println(my_array4[i][j][k][l]);
                        }
                    System.out.println("bye for now");
                    System.out.println();
                }
                System.out.println("bye for now, once again");
                System.out.println();
            }
            System.out.println("byier, 3rd time");
            System.out.println("(____-____)");
            System.out.println();
        }
        System.out.println("bye finally");
        */

        //Assignment 2b: Using enhanced for loop
        /*
        String [][][][] my_array4 = {{{{"python","java"},{"kotlin","javascript"}},{{"C++","C#"},{"Ruby","Dart"}}},{{{"Python","java"},{"kotlin","javascript"}},{{"C++","C#"},{"Ruby","Dart"}}}};
        for (String[][][] ion :my_array4) { //why double array?

            for (String[][] koko : ion){

                System.out.println(Arrays.deepToString (koko)+" ");
            }
            System.out.println();
        }
        */

        //Teachers Solution:
        /*
        String [][][][] my_array4 = {{{{"python","java"},{"kotlin","javascript"}},{{"C++","C#"},{"Ruby","Dart"}}},{{{"Python","java"},{"kotlin","javascript"}},{{"C++","C#"},{"Ruby","Dart"}}}};
        for (String ion[][][]:my_array4) { //why double array?

            for (String[][] koko:ion) {
                for (String[] kaka:koko) {
                    for (String kiki:kaka) {
                        System.out.println(kiki);
                    }
                    System.out.println("bye for now");
                    System.out.println();
                }
                System.out.println("Bye, once again");
            }
            System.out.println("Bye, finally");
        }
        System.out.println("Done");
        */

//Enhanced for loop for each loop
        //Code 1
        /*
        String [] myarray2 = {"python","java", "kotlin","javascript","Go","Ruby","C++"};
        for (String item:myarray2){
            System.out.println(item);
        }
         */

        //Code 2
        /*
        int [] myarray1 = {4,45,6};

        for (int num:myarray1){
            System.out.print(num+" ");
        }
        */

        //Code 3
        /*
        int [][] myArrays3 = {{1,2,4,8,12},{11,12,8,32},{15,120,90,12},{111,112}};

        for (int i[]:myArrays3) {

            for (int j : i) {
                System.out.print(j + " ");
            }

            System.out.println();
        }
        */

        /*
        () -> Method, constructor
        [] -> Arrays
        {} -> class, method, loop, conditional, all block of codes
        <> -> Generics
        */

//Recall on Methods and calling
        /*
        Scanner tester=new Scanner(System.in);  //this one accepts new input from user & creates a class "tester"
        //int num = num.nextInt();              //wrong, cause num in num.nextInt() is not a class/is not initialized
        //String bun = bun.nextln();            //wrong too. bun is uninitialized
        String name="aLEX";                     //normal naming convention
        String name1 = new String("alex");      //normal naming convention2, I think this is how to make a class out of a variable/initialize
        //name1.toLowerCase("wind");            //wrong way to call this name1
        String thin = name1.toLowerCase();      //right, name1 was initialized above

        int num= 29; //normal int naming convention
        //int cape = new int;//wrong
        //int cape = new int ("4");//wrong
        //int cape = new int String number1 = "4"; //recommended fix - still wrong
        //int cape = new int(4);//wrong too

        //Create a user defined class like thisInfo
            Scanner thisInfo = new Scanner(System.in); //Inbuiltclass Class = new Inbuiltclass(System.in);

        //Call any variable under the class
            //Datatype Variable = Class.method();
              double x = thisInfo.nextDouble();
              double y = thisInfo.nextDouble();
              int num = thisInfo.nextInt();
              String nameAge = thisInfo.next();

        //How to create object of a class & call the class
            //Datatype Variable = Class.method(); - call any variable

            //Inbuiltclass Class = new Inbuiltclass(System.in); - call user input class

            //ClassName variable(OR)object = new ClassName - create object of a class

        //You can also call inbuilt class like "Math"
        //double numerator = Math.pow(x,2) + Math.pow(y,3);

        System.out.println(name);
        System.out.println(num);
        */

        //Teacher Provided
        /*
        Scanner sc = new Scanner(System.in);
        sc.nextInt();       //nextInt is an Instance or non-static method
        Math.pow(2,4);      //pow is class or static method (because Math is a class, an inbuilt class)

        Static method or Class method (Follow come method): is a method that we can call directly or through the class itself.
        You can call it directly without creating the instance of the method.

        Instance method or non-static method: is the type of method that you call through the object of a class or instance of the call.
        Note: Object of a class is an instance of a class
        */

        /*
        Imagine we have a class MethodAssignment
        Static means we don't need to create the object of a class MethodAssignment to call it

        - Parameterized and non parameterized method
        - void means, dont return anything
        */
    }

}
